<?php require('fixed/header.phtml') ?>
<div class="container row">
    <div class="container s12 l12" id="ls-header">
        <h6 class="center helper-text"><strong>Test: Rubric Generator</strong></h6>
    </div>
    <div class=" container row s12 l12">
        <form name="name" method="post" action="<?php echo $_SERVER['PHP_SELF'];?>">
            <div class="container row s12 l12">
                <div class="col s9 l9">
                    <p>Test SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS</p>
                </div>
                <div class="input-field col s3 l3">
                    <select name="category_amount" class="browser-default" id="rubrics">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                    </select>
                </div><br>
            </div>

            <div class="container row s12 l12">
                <div class="col s9 l9">
                    <p>Test SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS</p>
                </div>
                <div class="input-field col s3 l3">
                    <select name="category_amount" class="browser-default" id="rubrics">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                    </select>
                </div><br>
            </div>

            <div class="container row s12 l12">
                <div class="col s9 l9">
                    <p>Test SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS</p>
                </div>
                <div class="input-field col s3 l3">
                    <select name="category_amount" class="browser-default" id="rubrics">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                    </select>
                </div><br>
            </div>

            <div class="btn-block col s12 l12">
                <input class="btn black right z-depth-2" type="submit"
                       name="submit" value="Submit">
            </div>
        </form>
    </div>
</div>
<?php require('fixed/footer.phtml') ?>
