    </main>

    <footer class="page-footer black" id="footer-container">
        <div class="container">
            <div class="row">
                <div class="col l6 s6">
                    <h6 class="white-text">Quick Links</h6>
                    <ul>
                        <li><a class="white-text" href="#!">Link 1</a></li>
                    </ul>
                </div>
                <div class="col l6 s6">
                    <h6 class="white-text">External Links</h6>
                    <ul>
                        <li><a class="white-text" href="#!">Link 1</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                Forum by
                <a class="brown-text text-lighten-3" target="_blank"
                   href="https://na.finalfantasyxiv.com/lodestone/character/20951952/">Xen Storm</a>
            </div>
        </div>
    </footer>
    <!--Optional JavaScript | Optimised loading-->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <script src="js/materialize.min.js"></script>
    <script src="/js/materialize-nav.js"></script>
  </body>
</html>